
<html>
<body>
    <form action="" method="POST">
        <script
            src="https://checkout.stripe.com/v2/checkout.js" class="stripe-button"
            data-key="pk_test_u7Yces86639pssqy4sHp9Yry"
            data-amount="2000"
            data-name="Demo Site"
            data-description="2 widgets ($20.00)"
            data-image="/128x128.png">
        </script>
    </form>
</body>
</html>